"""add child_count and social_family_quotient

Revision ID: 25cb8d4de41b
Revises: 
Create Date: 2025-07-23 06:15:00.986925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25cb8d4de41b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrower_profiles', sa.Column('child_count', sa.Integer(), nullable=True))
    op.add_column('borrower_profiles', sa.Column('social_family_quotient', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrower_profiles', 'social_family_quotient')
    op.drop_column('borrower_profiles', 'child_count')
    # ### end Alembic commands ###
